# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mirage 3.0.14 ruby lib

Gem::Specification.new do |s|
  s.name = "mirage"
  s.version = "3.0.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Leon Davis"]
  s.date = "2017-10-11"
  s.description = "Mirage aids testing of your applications by hosting mock responses so that your applications do not have to talk to real endpoints. Its accessible via HTTP and has a RESTful interface."
  s.executables = ["mirage"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/mirage",
    "lib/mirage/client.rb",
    "lib/mirage/client/cli_bridge.rb",
    "lib/mirage/client/client.rb",
    "lib/mirage/client/error.rb",
    "lib/mirage/client/helpers/method_builder.rb",
    "lib/mirage/client/request.rb",
    "lib/mirage/client/requests.rb",
    "lib/mirage/client/runner.rb",
    "lib/mirage/client/template.rb",
    "lib/mirage/client/template/configuration.rb",
    "lib/mirage/client/template/model.rb",
    "lib/mirage/client/template/model/common_methods.rb",
    "lib/mirage/client/template/model/instance_methods.rb",
    "lib/mirage/client/templates.rb",
    "lib/mirage/wait_methods.rb",
    "mirage_server.rb",
    "server/app.rb",
    "server/binary_data_checker.rb",
    "server/extensions/hash.rb",
    "server/extensions/object.rb",
    "server/helpers.rb",
    "server/helpers/http_headers.rb",
    "server/helpers/template_requirements.rb",
    "server/mock_response.rb",
    "server/mock_response_set.rb",
    "server/server.rb",
    "views/index.haml",
    "views/response.haml"
  ]
  s.homepage = "https://github.com/lashd/mirage"
  s.licenses = ["MIT"]
  s.post_install_message = "\n===============================================================================\nMirage v3:\n\nMirage has just gone up a major version from 2 to 3. If your project uses\na previous version take a look at https://github.com/lashd/mirage to see\nwhat's changed\n===============================================================================\n"
  s.rubygems_version = "2.4.8"
  s.summary = "Mirage is a easy mock server for testing your applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<childprocess>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<ptools>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<childprocess>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<ptools>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<childprocess>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<ptools>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra-contrib>, [">= 0"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
  end
end

