# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mirage}
  s.version = "1.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Leon Davis"]
  s.date = %q{2011-04-06}
  s.default_executable = %q{mirage}
  s.description = %q{Mirage aids testing of your applications by hosting mock responses so that your applications do not have to talk to real endpoints. Its accessible via HTTP and has a RESTful interface.}
  s.executables = ["mirage"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rvmrc",
    "Gemfile",
    "README.md",
    "VERSION",
    "bin/mirage",
    "features/client/clear.feature",
    "features/client/get.feature",
    "features/client/mirage_client.feature",
    "features/client/peek.feature",
    "features/client/save_and_revert.feature",
    "features/client/set.feature",
    "features/client/track.feature",
    "features/server/clear.feature",
    "features/server/command_line_iterface.feature",
    "features/server/file_responses.feature",
    "features/server/logging.feature",
    "features/server/peek.feature",
    "features/server/prime.feature",
    "features/server/response_templates.feature",
    "features/server/save_and_revert.feature",
    "features/server/set.feature",
    "features/server/set_default_response.feature",
    "features/server/set_with_a_delay.feature",
    "features/server/set_with_a_pattern.feature",
    "features/server/track.feature",
    "features/server/web_user_interface.feature",
    "features/step_definitions/my_steps.rb",
    "features/support/env.rb",
    "full_build.sh",
    "lib/config.ru",
    "lib/mirage.rb",
    "lib/mirage/client.rb",
    "lib/mirage/core.rb",
    "lib/mirage/util.rb",
    "lib/mirage/web.rb",
    "lib/start_mirage.rb",
    "lib/view/mirage/index.xhtml",
    "mirage.gemspec",
    "rakefile"
  ]
  s.homepage = %q{https://github.com/lashd/mirage}
  s.licenses = ["MIT"]
  s.post_install_message = %q{
===============================================================================
Thanks you for installing mirage.   

Run Mirage with:

mirage start                                   

For more information go to: https://github.com/lashd/mirage/wiki
===============================================================================
}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Mirage is a easy mock server for testing your applications}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, ["~> 1.1.0"])
      s.add_runtime_dependency(%q<ramaze>, [">= 2011.01.30"])
      s.add_runtime_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<childprocess>, ["~> 0.1"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
    else
      s.add_dependency(%q<rack>, ["~> 1.1.0"])
      s.add_dependency(%q<ramaze>, [">= 2011.01.30"])
      s.add_dependency(%q<mechanize>, [">= 1.0.0"])
      s.add_dependency(%q<childprocess>, ["~> 0.1"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<bundler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, ["~> 1.1.0"])
    s.add_dependency(%q<ramaze>, [">= 2011.01.30"])
    s.add_dependency(%q<mechanize>, [">= 1.0.0"])
    s.add_dependency(%q<childprocess>, ["~> 0.1"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<bundler>, [">= 0"])
  end
end

