# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mirage 3.0.9 ruby lib

Gem::Specification.new do |s|
  s.name = "mirage"
  s.version = "3.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Leon Davis"]
  s.date = "2014-12-08"
  s.description = "Mirage aids testing of your applications by hosting mock responses so that your applications do not have to talk to real endpoints. Its accessible via HTTP and has a RESTful interface."
  s.executables = ["mirage"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    ".simplecov",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "HISTORY",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/mirage",
    "features/.nav",
    "features/client/clear.feature",
    "features/client/configure.feature",
    "features/client/model.feature",
    "features/client/preview_responses.feature",
    "features/client/prime.feature",
    "features/client/put.feature",
    "features/client/readme.md",
    "features/client/requests.feature",
    "features/client/running.feature",
    "features/client/save_and_revert.feature",
    "features/client/start.feature",
    "features/client/stop.feature",
    "features/commandline_interface/help.feature",
    "features/commandline_interface/readme.md",
    "features/commandline_interface/start.feature",
    "features/commandline_interface/stop.feature",
    "features/logging.feature",
    "features/prime.feature",
    "features/readme.md",
    "features/requests/delete.feature",
    "features/requests/get.feature",
    "features/save_and_revert.feature",
    "features/step_definitions/my_steps.rb",
    "features/step_definitions/observation_steps.rb",
    "features/support/command_line.rb",
    "features/support/env.rb",
    "features/support/hooks.rb",
    "features/support/mirage.rb",
    "features/support/web.rb",
    "features/templates/delete.feature",
    "features/templates/get.feature",
    "features/templates/path_wildcards.feature",
    "features/templates/preview.feature",
    "features/templates/put.feature",
    "features/templates/put_with_substitutions.feature",
    "features/templates/readme.md",
    "features/templates/required_content.feature",
    "features/web_user_interface.feature",
    "full_build.sh",
    "lib/mirage/client.rb",
    "lib/mirage/client/cli_bridge.rb",
    "lib/mirage/client/client.rb",
    "lib/mirage/client/error.rb",
    "lib/mirage/client/helpers/method_builder.rb",
    "lib/mirage/client/request.rb",
    "lib/mirage/client/requests.rb",
    "lib/mirage/client/runner.rb",
    "lib/mirage/client/template.rb",
    "lib/mirage/client/template/configuration.rb",
    "lib/mirage/client/template/model.rb",
    "lib/mirage/client/template/model/common_methods.rb",
    "lib/mirage/client/template/model/instance_methods.rb",
    "lib/mirage/client/templates.rb",
    "mirage.gemspec",
    "mirage_server.rb",
    "server/app.rb",
    "server/binary_data_checker.rb",
    "server/extensions/hash.rb",
    "server/extensions/object.rb",
    "server/helpers.rb",
    "server/helpers/http_headers.rb",
    "server/helpers/template_requirements.rb",
    "server/mock_response.rb",
    "server/server.rb",
    "spec/client/cli_bridge_spec.rb",
    "spec/client/client_spec.rb",
    "spec/client/helpers/method_builder_spec.rb",
    "spec/client/request_spec.rb",
    "spec/client/requests_spec.rb",
    "spec/client/runner_spec.rb",
    "spec/client/template/configuration_spec.rb",
    "spec/client/template/model/common_methods_spec.rb",
    "spec/client/template/model/instance_methods_spec.rb",
    "spec/client/template/model_spec.rb",
    "spec/client/template_spec.rb",
    "spec/client/templates_spec.rb",
    "spec/resources/binary.file",
    "spec/server/binary_data_checker_spec.rb",
    "spec/server/helpers/http_headers_spec.rb",
    "spec/server/helpers/template_requirements_spec.rb",
    "spec/server/mock_response_spec.rb",
    "spec/server/server_spec.rb",
    "spec/spec_helper.rb",
    "tasks/application.rake",
    "tasks/packaging.rake",
    "tasks/tests.rake",
    "views/index.haml",
    "views/response.haml"
  ]
  s.homepage = "https://github.com/lashd/mirage"
  s.licenses = ["MIT"]
  s.post_install_message = "\n===============================================================================\nMirage v3:\n\nMirage has just gone up a major version from 2 to 3. If your project uses\na previous version take a look at https://github.com/lashd/mirage to see\nwhat's changed\n===============================================================================\n"
  s.rubygems_version = "2.2.2"
  s.summary = "Mirage is a easy mock server for testing your applications"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_runtime_dependency(%q<childprocess>, [">= 0"])
      s.add_runtime_dependency(%q<waitforit>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<ptools>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<childprocess>, [">= 0"])
      s.add_dependency(%q<waitforit>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<ptools>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sinatra-contrib>, [">= 0"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<childprocess>, [">= 0"])
    s.add_dependency(%q<waitforit>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<ptools>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sinatra-contrib>, [">= 0"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
  end
end

